services:
  redis-stack:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  chroma:
    image: ghcr.io/chroma-core/chroma
    ports:
      - 8000:8000
    volumes:
      - chroma_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/data

volumes:
  redis_data:
  chroma_data:
  qdrant_data:
